language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

cache: pip

notifications:
  email: false
  
os: linux

install:
  - pip install -r requirements.txt

script:
  - py.test