dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

cache: pip

version: ~> 1.0 # https://docs.travis-ci.com/user/build-config-validation

notifications:
  email: false
  
os: linux

install:
  - pip install -r requirements.txt

# command to run tests
script: pytest
